version: "{build}"

branches:
  except:
    - gh-pages
    - traits

skip_tags : true
shallow_clone: true

os: Visual Studio 2015 RC

environment:
  matrix:
    - title: vc2015
      compiler: Visual Studio 14 2015
    - title: vc2013
      compiler: Visual Studio 12 2013
    - title: vc2012
      compiler: Visual Studio 11 2012
    - title: vc2010
      compiler: Visual Studio 10 2010

install:
  - choco -y install cyg-get
  - cyg-get make
  - git clone --depth 1 https://github.com/CxxTest/cxxtest.git

build_script:
  - set CL=/I C:\projects\better-enums\cxxtest
  - set PATH=%PATH%;C:\projects\better-enums\cxxtest\bin;C:\tools\cygwin\bin
  - set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
  - cd test
  - make TITLE=%title% COMPILER="%compiler%" ms
